### PR TITLE
add prove/check section, random nits

### PR DESCRIPTION
**Pull request by qubenix**
I think this is close to finished. Note that I removed the section on checking binaries since it seems out of the scope of this guide. IMHO it's better to have tutorials on getmonero.org for verifying the binaries on Windows, Mac, and Linux. Then everyone who makes a guide or tutorial can link to the official Monero method instead of each person creating their own slightly different approach.

### CODE REVIEW

**Comment by erciccione** [comment]
The "checking binaries" section, was explicitly requested from a member of the community and i think it will be useful for everybody, since you can verify your binaries as soon as you download them, but i understand your point. Pinging for feedbacks: @dEBRUYNE

**Comment by qubenix** [comment]
I'm going to start working on the binary verification section. We can decide where it goes later. Here is a quick outline of the steps that I think are crucial. Please tell me what your thoughts are.

1. Install gnupg on system by using the gnupg docs.

2. Download compressed gui, hashes.txt, and fluffypony.asc from github via web browser to Downloads dir.

3. Get fluffys key from alternative source: `gpg --recv-keys BDA6BD7042B721C467A9759D7455C5E3C0CDCEB9`.

4. Double check keys from github are the same: `gpg --import Downloads/fluffypony.asc`.

5. Verify hashes file: `gpg --verify Downloads/hashes.txt`.

6. Verify the binary has same SHA256 as hashes.txt.

**Comment by erciccione** [comment]
Merging this PR for now, we can keep talking about binary verification in #5

**Comment by erciccione** [comment]
Are you going to push something else, or i can consider the guide done?

**Comment by qubenix** [comment]
I don't have anything left to push. After a quick read, I did just notice that after the pic in section 2.2.2 there's a nit. It says `...MyMonero. you need:`, but should be `...MyMonero. You need:`.

**Pull request merged**
